[profile.default]
solc-version = "0.8.15"
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./"}]
via-ir = true


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
